### ISSUE TITLE
[BUG] COM Freq Issue

### ISSUE THREAD

**Issue by N95JPL** [JPLogistics/MSFS_C152#37]
**Current version:**
 - Current mod version: V0.9.0
 - Current MSFS version: V1.10.2.0

**Describe the bug**
According to forum report, after around 30 Mins - pressing swap doesn't switch the Live Freq. to Standby but standby does move, so they end up the same!
Can't say I've noticed this but I shall investigate in our next long flight.
My initial thoughts would be that it's a FS Bug as we don't affect how the sim saves Vars

**To Reproduce**
Do a flight more than 30-45 mins
Try to change Freq!

**Expected behaviour**
Live goes to Standby as normal..?

**Screenshots**
N/A

**Additional context**
[Link to original forum report!](https://forums.flightsimulator.com/t/msfs-c152-community-v0-9-0/309284/119?u=n95jpl)

**Comment by danderio** [comment]
I was able to recreate this bug. For me, I was using the ATC flight following future and was instructed to contact a different approach frequency. When switched with the ATC menu, It sent me to a ATIS frequency of the local airport (instead of the approach frequency it instructed me to). When I tried to switch to the approach frequency manually (by swapping standby freq), it overwrote the both frequencies with same frequency number. This occurred approximately 30 minutes into the flight.

Next: I'll try to recreate the issue with default out of the box C152 and report results here.

**Comment by N95JPL** [comment]
Thanks for the report!
I personally don't really use the In-Game ATC - I will investigate this soon but it doesn't seem to happen if you don't use the ATC Menu to switch Frequency!

Thanks for trying it out!

**Comment by danderio** [comment]
Ok, so I confirmed this issue also occurs in the out-of-the-box C152. It starts by suddenly playing the local ATIS thru the same freq as the ATC freq. Then is just goes all crazy. Even the NAV radio doesn't respond correctly. I tried turning all radios off then on and they just kept receiving the ATIS and other local aircraft transmission. Tried a few flights with same result. I'm using version 1.11.6.0 of MSFS

**Comment by N95JPL** [comment]
Thankyou so much for all your effort!
If it's in the 'default' C152 then it's a much bigger issue than I expected!
I wonder if a Ticket has gone into ZenDesk about it?
I will check that out - it seems like an issue with the ATC element, as it doesn't do it at all when you don't use the in-game ATC (I solely fly with VATSIM) 

Thanks again for trying it all out!

Joshua
