### ISSUE TITLE
[BUG] Right Rudder input during Cruise

### ISSUE THREAD

**Issue by N95JPL** [JPLogistics/MSFS_C152#45]
**Current version:**
 - Current mod version: V0.9.2 & 0.9.3 BETA
 - Current MSFS version: V1.11.6.0

**Describe the bug**
Right rudder is required to fly straight during a cruise (countering excess force values for the prop rotation)

**To Reproduce**
1) Get to cruise
2) Aim direct at Checkpoint
3) See deviation, even with no wind

**Screeenshots to help explain your problem.**
N/A

**Additional context**
Reported by multiple users on Discord & Forums

**Comment by RetiredMan93231** [comment]
This issue will be affected greatly by my proposed changes to the aircraft Weight and Balance, and the proposed changes to the wing incidence and twist parameters. I recommend testing it again after implementing the proposed changes.

My test flights with the proposed changes show no problems with rudder input being required to maintain straight cruise flight.  But, I did notice the slip indicator (turn and bank ball) seems to be a little off even when standing still on the ground.

**Comment by N95JPL** [comment]
This one has been hindering us for a little while, initially I thought it was a W&B issue but it's not, the wing geometry settings should solve this mystery too!
Maybe it's to do with the way the Sim calculates wind moving up and around the wings?
Anyway, we will also try this tonight and report back!

**Comment by RetiredMan93231** [comment]
Since the C152 has no rudder trim control, the best way to eliminate the need for right rudder at cruise is to apply right thrust to the engine & prop.  About 2 degrees of right thrust is needed to counter the P-factor and torque effects at cruise....  The torque and p-factor scalers must also be set correctly...

[MSFS C152  Engines Update.txt](https://github.com/JPLogistics/MSFS_C152/files/5681337/MSFS.C152.Engines.Update.txt)

[MSFS C152 Flight Model Update.txt](https://github.com/JPLogistics/MSFS_C152/files/5681340/MSFS.C152.Flight.Model.Update.txt)

**Comment by N95JPL** [comment]
I tried these values, but i got an awful list to the left hand side?
Maybe it was when I was changing other stuff too, I will try again!
Thanks!

**Comment by N95JPL** [comment]
This should be resolved as of V0.9.3 Beta 5

Pending closure, awaiting public release!
