### ISSUE TITLE
Left banking from level flight

### ISSUE THREAD

**Issue by T1gger65** [JPLogistics/MSFS_C152#5]
A few of us were discussing this this MSFS_C152 mod based on DFR30q's C152X work in the MSFS forums. Several of us are seeing strong left banking from trimmed level flight. Every time I go hands off on the Honeycomb yoke the C152 banks hard to the left and won't maintain straight flight. If I revert to the C152X mod the issue is no longer present.

**Comment by oliverpope03** [comment]
We have also spotted this but we since we were flying with left seat only, not passenger we presumed it was the weight of the pilot tilting the scale to the left, we will investigate this further to see if theres a deeper issue

**Comment by N95JPL** [comment]
Hello!
Firstly, thanks for posting!

The default payload on this mod actually is Left Hand heavy, the copilot seat is empty (I was meant to change this for the release, it's because I have my payload as if it was just me and my rucksack in the plane!)

Have you checked your Weight & Balance?

I didn't notice a left hand bank when I added a similarly weighed copilot

Also, can you post a link to the forum post?

Thanks!

**Comment by T1gger65** [comment]
Ok that was it. Added the copilot and its flying straight with balanced loadout

I'm so used to the 152 and 172 being setup with copilot and even weight I never even checked that. Not a real pilot and currently don't have rudder pedals. I have auto-rudder enabled in the sim but I guess it doesn't compensate for uneven load distribution.

**Comment by oliverpope03** [comment]
Uneven payload would probably be fixed by aileron input, yes its kind of an odd one, ill fix the default to have copilot and pilot so its balanced, however yes because its such a light aircraft slight things like that seem to affect it alot.
